active_broker: sharekhan

brokers:
  zerodha:
    api_key: "YOUR_API_KEY"
    api_secret: "YOUR_API_SECRET"
    access_token: "" # Optional: Fill this if you have a valid access token

  sharekhan:
    api_key: "YOUR_API_KEY"
    secret_key: "YOUR_SECRET_KEY"
    request_token: "request token received after login"

  interactive_brokers:
    host: "127.0.0.1"
    port: 7497 # 7497 for paper trading, 7496 for live
    client_id: 1
